// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Enums from './Enums'

export const Data = {
  Enums,
}

export default Data
