// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import '@inertiajs/core'

declare module '@inertiajs/core' {
  export interface InertiaConfig {
    sharedPageProps: {
      auth: { user: string | null }
      flash: { success: unknown }
      errors: Record<string, Record<number | string, string>>
    }
  }
}
