// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export namespace Inertia {
    export type SharedData = { auth: { user: string | null }, flash: { success: unknown }, errors: Record<string, Record<number | string, string>> }
}

export namespace App {
    export namespace Data {
        export namespace Enums {
            /**
             * @see [\App\Data\Enums\AccountStatus](/Users/joecianflone/projects/me/platform/backend/app/Data/Enums/AccountStatus.php)
             */
            export type AccountStatus = 'active' | 'closed' | 'inactive' | 'locked' | 'pending'

            /**
             * @see [\App\Data\Enums\HttpResponse](/Users/joecianflone/projects/me/platform/backend/app/Data/Enums/HttpResponse.php)
             */
            export type HttpResponse = 400 | 201 | 403 | 404 | 200 | 500 | 401 | 422
        }
    }
}

export namespace Closure {
    export namespace __invoke {
        /**
         * @see [\Closure::__invoke](/Users/joecianflone/projects/me/platform/backend/vendor/laravel/framework/src/Illuminate/Foundation/Configuration/ApplicationBuilder.php)
         */
        export type Request = Record<string, unknown>
    }
}