// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const ACTIVE = "active"
export const CLOSED = "closed"
export const INACTIVE = "inactive"
export const LOCKED = "locked"
export const PENDING = "pending"

/**
 * @see [App\Data\Enums\AccountStatus](/Users/joecianflone/projects/me/platform/backend/app/Data/Enums/AccountStatus.php)
 */
export const AccountStatus = { ACTIVE, CLOSED, INACTIVE, LOCKED, PENDING } as const

export default AccountStatus