// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const BAD_REQUEST = 400
export const CREATED = 201
export const FORBIDDEN = 403
export const NOT_FOUND = 404
export const OK = 200
export const SERVER_ERROR = 500
export const UNAUTHORIZED = 401
export const UNPROCESSABLE = 422

/**
 * @see [App\Data\Enums\HttpResponse](/Users/joecianflone/projects/me/platform/backend/app/Data/Enums/HttpResponse.php)
 */
export const HttpResponse = {
  BAD_REQUEST,
  CREATED,
  FORBIDDEN,
  NOT_FOUND,
  OK,
  SERVER_ERROR,
  UNAUTHORIZED,
  UNPROCESSABLE,
} as const

export default HttpResponse
