// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import HttpResponse from "./HttpResponse";
import AccountStatus from "./AccountStatus";

export const Enums = {
    HttpResponse,
    AccountStatus,
}

export default Enums